### PR TITLE
fix for displaying logs correctly

### PR DESCRIPTION
**Pull request by impca**
Hi,

I had to change the code that handles the processing of messages. When hubot logged a message that contained failed output from a shell command {"killed":false,"code":1,"signal":null} , the function escapeHtml started throwing exceptions, because event.message wasn't string, but object. No further messages were processed and webpage with logs for that particular day would not display.

I have added a failsafe. If escapeHtml fails, the message is silenty discarded and logged. 

Alternatively, it is possible to convert the message to a string and display that string instead. 

You can decide which one is better (log and discard, or display) and merge it appropriately.

Thanks.

### CODE REVIEW

**Comment by impca** [comment]
I added some for changes to handle private messages on IRC.

**Comment by anarcher** [comment]
Wow, very interesting! Thank you very much for the contribution.  I'm sorry for too late. I didn't know this PR :-(  I'll check this PR soon. Thanks!

**Comment by anarcher** [comment]
IMO, Display should better than log and discard. What do you think?

**Comment by anarcher** [comment]
@impca I released `v0.0.11` based on your PR. Thanks. :-)

**Comment by impca** [comment]
I guess displaying the output is better. If there are no other messages it allows you to see that the command was terminated.

**Comment by anarcher** [comment]
I agree it. displaying the output is better.

**Pull request merged**
